#!/bin/bash
APP_DIR="vehicleCANProcessor"

if [ -d $APP_DIR ];
then
	echo "$APP_DIR has been found - remove first"
	rm -rf "$APP_DIR"
fi

git clone https://github.com/pawelwojtowicz/vehicleCANProcessor.git -b kafkaEdition

sudo docker build -t node-vehicle-data-sink "$APP_DIR"

