#!/bin/bash
APP_DIR="vehicleCANProcessor"

if [ -d $APP_DIR ];
then
	echo "$APP_DIR has been found - remove first"
	rm -rf "$APP_DIR"
fi

git clone https://github.com/pawelwojtowicz/vehicleCANProcessor.git

cp dockerfile_webfeed vehicleCANProcessor/dockerfile
cp .dockerignore vehicleCANProcessor/

cd vehicleCANProcessor

sudo docker build -t ibisdev/node-webfeed .

