#!/bin/bash
docker run -d -p 6379:6379 redis
docker run --network host -p 8090:8090 -e "SRV_NAME=webfeed001" -d ibisdev/node-vehicle_handler webfeed
docker run --network host -p 8080:8080 -e "SRV_NAME=vhHandler001" -d ibisdev/node-vehicle_handler vhHandler
docker run --network host -p 8081:8080 -e "SRV_NAME=vhHandler002" -d ibisdev/node-vehicle_handler vhHandler
docker run --network host -p 8082:8080 -e "SRV_NAME=vhHandler003" -d ibisdev/node-vehicle_handler vhHandler

